sudo: false
language: python
branches:
    only:
    - TEST_flask
matrix:
    include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.3"
      env: TOXENV=py33
    - python: "2.6"
      env: TOXENV=py26
    - python: "3.5"
      env: TOXENV=py35
    - python: "pypy"
      env: TOXENV=pypy
    - python: "pypy3"
      env: TOXENV=pypy3
    allow_failures:
    - env: TOXENV=py35
    - env: TOXENV=pypy
    - env: TOXENV=pypy3
install:
- if [[ ! -z $TOXENV ]]; then pip install tox; fi
- if [[ ! -z $TOXENV ]]; then pip install flake8; fi
- if [[ ! -z $TOXENV ]]; then pip install pep8-naming; fi
- if [[ $TOXENV == 'py27' ]]; then pip install coveralls; fi
script:
- if [[ ! -z $TOXENV ]]; then tox -e $TOXENV; fi
after_success:
- if [[ $TOXENV == 'py27' ]]; then coveralls; fi
notifications:
    email: false
