os:
    - linux
    - osx
language: python
branches:
    except:
    - gh-pages
env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=checkers
matrix:
  allow_failures:
  - env: TOXENV=pypy
  - env: TOXENV=checkers
install:
- pip install tox
- pip install flake8
- pip install pep8-naming
- pip install coveralls
script:
- "if [[ ! -z $TOXENV ]]; then tox -e $TOXENV; fi"
after_success:
- "if [[ $TOXENV == 'py27' ]]; then coveralls; fi"
