language: python

matrix:
    include:
    - python: "2.7"
      env: MXENV=py27
    - python: "3.3"
      env: MXENV=py33
    - python: "3.4"
      env: MXENV=py34
    - python: "3.5"
      env: MXENV=py35
    - python: "pypy"
      env: MXENV=pypy

install:
  - "pip install -r requirements.txt"

script:
  - "./run-test.sh"

notifications:
    email: false
